package com.abhiai.abhiai_backend.service;
import java.util.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.abhiai.abhiai_backend.dto.common.PageResponse;import com.abhiai.abhiai_backend.dto.follow.*;import com.abhiai.abhiai_backend.entity.*;import com.abhiai.abhiai_backend.exception.*;import com.abhiai.abhiai_backend.repository.*;
@Service public class FollowRequestService{
 private final FollowRequestRepository requests;private final FollowRepository follows;private final UserRepository users;private final BlockPolicyService blocks;
 public FollowRequestService(FollowRequestRepository r,FollowRepository f,UserRepository u,BlockPolicyService b){requests=r;follows=f;users=u;blocks=b;}
 @Transactional public FollowRequestResponse request(UUID actor,UUID targetId){blocks.requireInteractionAllowed(actor,targetId);User a=user(actor),t=user(targetId);if(t.getAccountPrivacy()!=AccountPrivacy.PRIVATE)throw new UnauthorizedActionException("Public accounts can be followed directly");FollowRequest fr=requests.findByRequesterIdAndTargetId(actor,targetId).orElseGet(()->new FollowRequest(a,t));fr.status(FollowRequestStatus.PENDING);return FollowRequestResponse.from(requests.saveAndFlush(fr));}
 @Transactional public void decide(UUID actor,UUID id,boolean accept){FollowRequest r=find(id);if(!r.getTarget().getId().equals(actor))throw new UnauthorizedActionException("Only the recipient can decide this request");r.status(accept?FollowRequestStatus.ACCEPTED:FollowRequestStatus.REJECTED);requests.save(r);if(accept&&!follows.existsByFollowerIdAndFollowingId(r.getRequester().getId(),actor)){follows.save(new Follow(r.getRequester(),r.getTarget()));users.incrementFollowingCount(r.getRequester().getId());users.incrementFollowerCount(actor);}}
 @Transactional public void cancel(UUID actor,UUID id){FollowRequest r=find(id);if(!r.getRequester().getId().equals(actor))throw new UnauthorizedActionException("Only the requester can cancel");r.status(FollowRequestStatus.CANCELLED);}
 @Transactional(readOnly=true) public PageResponse<FollowRequestResponse> inbox(UUID actor,Pageable p){return PageResponse.from(requests.findByTargetIdAndStatus(actor,FollowRequestStatus.PENDING,PageRequest.of(Math.max(0,p.getPageNumber()),Math.min(100,Math.max(1,p.getPageSize())))),FollowRequestResponse::from);}
 private User user(UUID id){return users.findById(id).orElseThrow(UserNotFoundException::new);}private FollowRequest find(UUID id){return requests.findById(id).orElseThrow(UserNotFoundException::new);}
}
