package com.abhiai.abhiai_backend.ai.pipeline;

public enum Intent {
    GENERAL_CHAT, EDUCATION, CODING, REASONING, CREATIVE_WRITING, SUMMARIZATION,
    DOCUMENT_ANALYSIS, IMAGE_GENERATION, CURRENT_INFORMATION, DATA_ANALYSIS, PLANNING
}
