package com.abhiai.abhiai_backend.service;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import java.util.*; import org.junit.jupiter.api.BeforeEach; import org.junit.jupiter.api.Test; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.Mock; import org.mockito.junit.jupiter.MockitoExtension; import org.springframework.test.util.ReflectionTestUtils;
import com.abhiai.abhiai_backend.dto.report.CreateReportRequest; import com.abhiai.abhiai_backend.entity.*; import com.abhiai.abhiai_backend.exception.*; import com.abhiai.abhiai_backend.repository.*;
@ExtendWith(MockitoExtension.class)
class ContentReportServiceTest {
 @Mock ContentReportRepository reports; @Mock UserRepository users; @Mock PostAccessService postAccess; @Mock PostReplyRepository postReplies; @Mock ArticleCommentRepository articleComments; @Mock CommunityRepository communities; @Mock DirectMessageRepository directMessages; @Mock DirectConversationRepository directConversations; @Mock GroupMessageRepository groupMessages; @Mock GroupParticipantRepository groupParticipants;
 private ContentReportService service; private User reporter,author; private Post post; private final UUID reporterId=UUID.randomUUID(),authorId=UUID.randomUUID(),postId=UUID.randomUUID();
 @BeforeEach void setup(){service=new ContentReportService(reports,users,postAccess,postReplies,articleComments,communities,directMessages,directConversations,groupMessages,groupParticipants);reporter=user(reporterId,"reporter");author=user(authorId,"author");post=new Post(author,"Reported post",PostVisibility.PUBLIC);ReflectionTestUtils.setField(post,"id",postId);}
 @Test void createsAValidatedPostReport(){when(users.findById(reporterId)).thenReturn(Optional.of(reporter));when(postAccess.findViewablePost(reporterId,postId)).thenReturn(post);when(reports.saveAndFlush(any())).thenAnswer(call->{ContentReport value=call.getArgument(0);ReflectionTestUtils.setField(value,"id",UUID.randomUUID());return value;});var result=service.create(reporterId,new CreateReportRequest(ReportTargetType.POST,null,postId,ReportReason.SPAM,"Repeated advertising"));assertEquals(ReportStatus.PENDING,result.status());assertEquals("Repeated advertising",result.details());}
 @Test void rejectsReportingOwnContent(){when(users.findById(authorId)).thenReturn(Optional.of(author));when(postAccess.findViewablePost(authorId,postId)).thenReturn(post);assertThrows(InvalidContentReportException.class,()->service.create(authorId,new CreateReportRequest(ReportTargetType.POST,null,postId,ReportReason.OTHER,null)));verify(reports,never()).saveAndFlush(any());}
 @Test void requiresContextForCommentReports(){when(users.findById(reporterId)).thenReturn(Optional.of(reporter));assertThrows(InvalidContentReportException.class,()->service.create(reporterId,new CreateReportRequest(ReportTargetType.COMMENT,null,UUID.randomUUID(),ReportReason.HARASSMENT,null)));}
 @Test void rejectsDuplicateReportsBeforeWriting(){when(users.findById(reporterId)).thenReturn(Optional.of(reporter));when(postAccess.findViewablePost(reporterId,postId)).thenReturn(post);when(reports.existsByReporterIdAndTargetTypeAndTargetContextAndTargetId(reporterId,ReportTargetType.POST,null,postId)).thenReturn(true);assertThrows(DuplicateContentReportException.class,()->service.create(reporterId,new CreateReportRequest(ReportTargetType.POST,null,postId,ReportReason.SPAM,null)));verify(reports,never()).saveAndFlush(any());}
 private User user(UUID id,String username){User value=new User(username,username,username+"@example.com","hash");ReflectionTestUtils.setField(value,"id",id);return value;}
}
